/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PantryIndexRouteImport } from './routes/pantry/index'
import { Route as GroceryIndexRouteImport } from './routes/grocery/index'
import { Route as PantryItemIdRouteImport } from './routes/pantry/$itemId'
import { Route as GroceryListIdRouteImport } from './routes/grocery/$listId'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryIndexRoute = PantryIndexRouteImport.update({
  id: '/pantry/',
  path: '/pantry/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryIndexRoute = GroceryIndexRouteImport.update({
  id: '/grocery/',
  path: '/grocery/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryItemIdRoute = PantryItemIdRouteImport.update({
  id: '/pantry/$itemId',
  path: '/pantry/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListIdRoute = GroceryListIdRouteImport.update({
  id: '/grocery/$listId',
  path: '/grocery/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/pantry/$itemId': typeof PantryItemIdRoute
  '/grocery/': typeof GroceryIndexRoute
  '/pantry/': typeof PantryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/pantry/$itemId': typeof PantryItemIdRoute
  '/grocery': typeof GroceryIndexRoute
  '/pantry': typeof PantryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/grocery/$listId': typeof GroceryListIdRoute
  '/pantry/$itemId': typeof PantryItemIdRoute
  '/grocery/': typeof GroceryIndexRoute
  '/pantry/': typeof PantryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/users'
    | '/auth/sign-in'
    | '/grocery/$listId'
    | '/pantry/$itemId'
    | '/grocery/'
    | '/pantry/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/users'
    | '/auth/sign-in'
    | '/grocery/$listId'
    | '/pantry/$itemId'
    | '/grocery'
    | '/pantry'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin/users'
    | '/auth/sign-in'
    | '/grocery/$listId'
    | '/pantry/$itemId'
    | '/grocery/'
    | '/pantry/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthSignInRoute: typeof AuthSignInRoute
  GroceryListIdRoute: typeof GroceryListIdRoute
  PantryItemIdRoute: typeof PantryItemIdRoute
  GroceryIndexRoute: typeof GroceryIndexRoute
  PantryIndexRoute: typeof PantryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/': {
      id: '/pantry/'
      path: '/pantry'
      fullPath: '/pantry/'
      preLoaderRoute: typeof PantryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/': {
      id: '/grocery/'
      path: '/grocery'
      fullPath: '/grocery/'
      preLoaderRoute: typeof GroceryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/$itemId': {
      id: '/pantry/$itemId'
      path: '/pantry/$itemId'
      fullPath: '/pantry/$itemId'
      preLoaderRoute: typeof PantryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery/$listId': {
      id: '/grocery/$listId'
      path: '/grocery/$listId'
      fullPath: '/grocery/$listId'
      preLoaderRoute: typeof GroceryListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthSignInRoute: AuthSignInRoute,
  GroceryListIdRoute: GroceryListIdRoute,
  PantryItemIdRoute: PantryItemIdRoute,
  GroceryIndexRoute: GroceryIndexRoute,
  PantryIndexRoute: PantryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
